export const GAME_STATES = {
  LOAD: 'LOAD',
  TITLE: 'TITLE',
  INTRO: 'INTRO',
  PROBLEM: 'PROBLEM',
  CHOOSE: 'CHOOSE',
  TIMING: 'TIMING',
  RESOLVE: 'RESOLVE',
  EXPLAIN: 'EXPLAIN',
  FINISH_LINE: 'FINISH_LINE',
  FINISH_ANIM: 'FINISH_ANIM',
  VICTORY: 'VICTORY',
  DEFEAT: 'DEFEAT',
}
